<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAssignProduct
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $productList = $block->getLayout()->createBlock(\Webkul\MpAssignProduct\Block\Product\ProductList::class);
    $helper = $productList->getHelperObject();
    $braspagPaymentSplitConfig = $block->getBraspagPaymentSplitConfig();
    $isPartner = $productList->getHelperObject('marketplaceHelper')->isSeller();
    $symbol = $productList->getHelperObject('marketplaceHelper')->getCurrencySymbol();
?>

<?php if ($isPartner == 1 && $braspagPaymentSplitConfig->getPaymentSplitMarketPlaceGeneralBraspagFinancialPageEnabled()): ?>

    <form method="post" action="<?= /* @noEscape */ $block->getUrl('braspag/paymentSplit_sellerProfile/save'); ?>"
    id="wk_mpassignproduct_form" enctype="multipart/form-data" data-mage-init='{"validation":{}}'>
        <input type="hidden" name="form_key" value="<?= /* @noEscape */ $block->getFormKey(); ?>">
        <fieldset class="fieldset">
            <?= /* @noEscape */ $block->getFormKeyBlockHtml(); ?>
            <legend class="legend">
                <span><?= /* @noEscape */ __("Seller Bank Account"); ?></span>
            </legend>

            <div class="field required">
                <label for="bank_code" class="label">
                    <span><?= /* @noEscape */ __("Bank Code");?></span>
                </label>
                <div class="control">
                    <input value="<?= /* @noEscape */ "" ?>" type="text"
                    data-validate="{required:true}" class="input-text required-entry"
                     title="<?= /* @noEscape */ __('Bank Code'); ?>" name="bank_code" id="bank_code" aria-required="true">
                </div>
            </div>

            <div class="field required">
                <label for="bank_account_type" class="label">
                    <span><?= /* @noEscape */ __("Bank Account Type"); ?></span>
                </label>
                <div class="control">
                    <select aria-required="true" name="bank_account_type" id="bank_account_type"
                    class="required-entry" title="<?= /* @noEscape */ __("Bank Account Type"); ?>"
                    data-validate="{'validate-select':true}">
                        <?php foreach (['CheckingAccount' => 'Conta corrente', 'SavingsAccount' => 'Conta poupança'] as $value => $label): ?>
                            <option value="<?= /* @noEscape */ $value; ?>">
                                <?= /* @noEscape */ __($label); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="field required">
                <label for="bank_account_number" class="label">
                    <span><?= /* @noEscape */ __("Bank Account Number"); ?></span>
                </label>
                <div class="control">
                    <input value="<?= /* @noEscape */ ""; ?>" type="text"
                           data-validate="{required:true}" class="input-text required-entry validate-number"
                           title="<?= /* @noEscape */ __('BankVerifierDigit'); ?>" name="bank_account_number" id="bank_account_number" aria-required="true">
                </div>
            </div>

            <div class="field required">
                <label for="bank_account_verifier_digit" class="label">
                    <span><?= /* @noEscape */ __("Bank Account Verifier Digit"); ?></span>
                </label>
                <div class="control">
                    <input value="<?= /* @noEscape */ ""; ?>" type="text"
                           data-validate="{required:true}" class="input-text required-entry validate-number"
                           title="<?= /* @noEscape */ __('Bank Account Verifier Digit'); ?>" name="bank_account_verifier_digit" id="bank_account_verifier_digit" aria-required="true">
                </div>
            </div>

            <div class="field required">
                <label for="bank_account_operation" class="label">
                    <span><?= /* @noEscape */ __("Bank Account Operation"); ?></span>
                </label>
                <div class="control">
                    <input value="<?= /* @noEscape */ ""; ?>" type="text"
                           data-validate="{required:true}" class="input-text required-entry validate-number"
                           title="<?= /* @noEscape */ __('Bank Account Operation'); ?>" name="bank_account_operation" id="bank_account_operation" aria-required="true">
                </div>
            </div>

            <div class="field required">
                <label for="bank_agency_number" class="label">
                    <span><?= /* @noEscape */ __("Bank Agency Number"); ?></span>
                </label>
                <div class="control">
                    <input value="<?= /* @noEscape */ ""; ?>" type="text"
                           data-validate="{required:true}" class="input-text required-entry validate-number"
                           title="<?= /* @noEscape */ __('Bank Agency Number'); ?>" name="bank_agency_number" id="bank_agency_number" aria-required="true">
                </div>
            </div>

            <div class="field required">
                <label for="bank_agency_digit" class="label">
                    <span><?= /* @noEscape */ __("Bank Agency Digit"); ?></span>
                </label>
                <div class="control">
                    <input value="<?= /* @noEscape */ ""; ?>" type="text"
                           data-validate="{required:true}" class="input-text required-entry validate-number"
                           title="<?= /* @noEscape */ __('Bank Agency Digit'); ?>" name="bank_agency_digit" id="bank_agency_digit" aria-required="true">
                </div>
            </div>

            <div class="field required">
                <label for="bank_account_owner_document_type" class="label">
                    <span><?= /* @noEscape */ __("Bank Account Owner Document Type"); ?></span>
                </label>
                <div class="control">
                    <select aria-required="true" name="bank_account_owner_document_type" id="bank_account_owner_document_type"
                            class="required-entry" title="<?= /* @noEscape */ __("Bank Account Owner Document Type"); ?>"
                            data-validate="{'validate-select':true}">
                        <?php foreach (['Cpf' => 'CPF', 'Cnpj' => 'CNPJ'] as $value => $label): ?>
                            <option value="<?= /* @noEscape */ $value; ?>">
                                <?= /* @noEscape */ __($label); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="field required">
                <label for="bank_account_owner_document_number" class="label">
                    <span><?= /* @noEscape */ __("Bank Account Owner Document Number"); ?></span>
                </label>
                <div class="control">
                    <input value="<?= /* @noEscape */ ""; ?>" type="text"
                           data-validate="{required:true}" class="input-text required-entry validate-number"
                           title="<?= /* @noEscape */ __('Bank Account Owner Document Number'); ?>" name="bank_account_owner_document_number" id="bank_account_owner_document_number" aria-required="true">
                </div>
            </div>

            <?= $block->getChildHtml(); ?>
            <div class="field required">
                <div class="control">
                    <button class="button wk-product-save-btn" type="submit">
                        <span><span><?= /* @noEscape */ __("Save"); ?></span></span>
                    </button>
                </div>
            </div>
        </fieldset>
    </form>
<?php elseif ($braspagPaymentSplitConfig->getPaymentSplitMarketPlaceGeneralBraspagFinancialPageEnabled()): ?>
    <h2 class="wk-mp-error-msg">
        <?= /* @noEscape */ __("To Become Seller Please Contact to Admin."); ?>
    </h2>
<?php else: ?>
    <h2 class="wk-mp-error-msg">
        <?= /* @noEscape */ __("Invalid Page."); ?>
    </h2>
<?php endif; ?>
